version: '2.1'

volumes:
    data1: {}
    data2: {}
    data3: {}

services:

    oklog1:
        container_name: oklog1
        image: oklog
        command: [
            "-peer", "oklog2:10009",
            "-peer", "oklog3:10009"
        ]
        ports:
            - "10010:10000"
            - "10011:10001"
            - "10012:10002"
            - "10013:10003"
            - "10019:10009"
        volumes:
            - data1:/data

    oklog2:
        container_name: oklog2
        image: oklog
        command: [
            "-peer", "oklog1:10009",
            "-peer", "oklog3:10009"
        ]
        ports:
            - "10020:10000"
            - "10021:10001"
            - "10022:10002"
            - "10023:10003"
            - "10029:10009"
        volumes:
            - data2:/data

    oklog3:
        container_name: oklog3
        image: oklog
        command: [
            "-peer", "oklog1:10009",
            "-peer", "oklog2:10009"
        ]
        ports:
            - "10030:10000"
            - "10031:10001"
            - "10032:10002"
            - "10033:10003"
            - "10039:10009"
        volumes:
            - data3:/data

    logspout:
        image: gliderlabs/logspout
        command:
            - "raw+tcp://oklog1:10001"
        ports:
            - "8000:80"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"